### ISSUE TITLE
Different values in shared view of grid/cloud data vs individual databases

### ISSUE THREAD

**Issue by sarahbyrnie** [apel/grafana-dashboards#103]
Looking on the resource manager dashboard at the previous and projected usage table. If you switch from using the grid and cloud databases separately to the shared VCombinedSummaries view, there are some inconsistencies in the values.

**Comment by tofu-rocketry** [comment]
Needs more investigation to check if the `VCombinedSummaries` view is doing what we want - hopefully it's the old calculations that are wrong.
