### ISSUE TITLE
Create Python script to assign colours to panels

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#11]

**Comment by tswinb** [comment]
Created a script to assign pre-defined colour mappings to all panels on a JSON file which can then be imported into Grafana (or overwrite an existing one). Had an issue with piecharts not displaying the chosen colours correctly which appears to be resolved by choosing colours only through Hex format. Tried to choose colours for maximum readability and distinguishability but this can probably be improved over time.

**Comment by tofu-rocketry** [comment]
Do you want to open a pull request for the script? It can just live in the repo's root for now.
