### ISSUE TITLE
Make config compatible with Grafana 8.0+

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#122]
The newer versions of Grafana don't seem to like our current dashboards and database connections.

https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v80

**Comment by tofu-rocketry** [comment]
Partially resolved by #124 but fixes also needed for non-IRIS dashboards (cloud and GridPP).

**Comment by jounaidr** [comment]
Remaining dashboard fixed in #127 :)
