### ISSUE TITLE
Graph tooltip displays incorrect values when missing data

### ISSUE THREAD

**Issue by tswinb** [apel/grafana-dashboards#14]
When using the graph hover tooltip on the main top graph some of the values are incorrect because they are showing the nearest number rather than 0. This happens because there is no data for that month with that VO. Grafana still expects a database entry for them (either with null or 0 value) with which to populate the graph. Because of the way the data comes in, month-VO combinations with no data to show have no database entries. 

Possible solution would be to insert dummy record summaries for month-VO combinations with no data.

**Comment by tswinb** [comment]
Possibly change Hover Tooltip mode from 'All Series' to 'Single'?

**Comment by tofu-rocketry** [comment]
Yup, we'll change it to "single".
