### ISSUE TITLE
Make estimated usage forecast most distinct

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#152]
Hashed fill probably isn't possible. Gradient, different colour?

**Comment by tofu-rocketry** [comment]
And add reference in Help page.

**Comment by rowan04** [comment]
I am unable to find a way to create a gradient or hashed fill. This leaves changing the colour, and also the transparency. What colour can you think to change it to?
This is what it is currently, and it needs making more distinct (this is with the Diamond activity removed so you can see the Estimated Total Usage).
![image](https://github.com/apel/grafana-dashboards/assets/90393428/e469bbcf-ef46-4b4a-aa83-56b134a18d71)

**Comment by rowan04** [comment]
Here are a couple suggestions:
![image](https://github.com/apel/grafana-dashboards/assets/90393428/b2613800-e6b2-4916-8d7c-7289d2d132a1)

![image](https://github.com/apel/grafana-dashboards/assets/90393428/1f6a857a-0907-4270-87ae-eb7d72443cea)

![image](https://github.com/apel/grafana-dashboards/assets/90393428/93dec47a-4f35-4e29-8983-3ee2a0d7cb9d)

![image](https://github.com/apel/grafana-dashboards/assets/90393428/adfc6bda-1fb6-401b-9aa0-f47d0384f204)

**Comment by rowan04** [comment]
The transparency of it could be changed.
Or do you have any other ideas of how it could be made more distinct?

**Comment by rowan04** [comment]
> I would say either the first or second colours stand out the most of the four. Maybe a slight preference for number 2.
> 
> I wonder could the estaimted useage be toggled on and off with a drop dwon menu or similar? If it can be, maybe we can get away with having a solid colour for the estimated usage, which I think would stand out even more.

Yeah it should be able to be made into a drop down

**Comment by rowan04** [comment]
![image](https://github.com/apel/grafana-dashboards/assets/90393428/35121cfd-31c3-4456-b4fe-305179e98659)

anyone have a preference for which colour, or a suggestion?

**Comment by gregcorbett** [comment]
4 or 6 get my inital vote.

**Comment by rowan04** [comment]
> 4 or 6 get my inital vote.

yeah i quite like 6
