### ISSUE TITLE
Interval of data updates will lead to slightly inaccurate projection values

### ISSUE THREAD

**Issue by tswinb** [apel/grafana-dashboards#28]
APEL tables are only updated once a day which causes misleading projections during certain periods of the day. 

_Fictional example:_
Today's date: 08/11
Value so far this month for grid: 100
Projected value at the end of the month: 100/8 * 30 = 375
Let's say that the tables are updated at 2pm every day. 
Tomorrow morning the projection graph will be recalculated as: 100/9 * 30 = 333.33
Arguably there is no reason for this dip as we do not know what the data will show for tomorrow (we should stick to today's value)

_Possible Solution:_ use the latest update time in the table as today's date in the calculation.

**Comment by tswinb** [comment]
The solution of using latest update time is deployed

**Comment by tofu-rocketry** [comment]
Ah, hadn't realised. :+1:
