### ISSUE TITLE
Improve clarity of units

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#3]

**Comment by tswinb** [comment]
Suggestion:
'Elapsed time * Number of Processors (months)' -> 'Average Cores Used Per Month'

**Comment by tofu-rocketry** [comment]
I think we should do the following:

- [ ] Change titles to "Average Core Usage by...." for any chart titles with "'Elapsed time * Number of Processors (months) by...". We'll leave the y-axis label for the moment.
- [ ] Standardise on "Activity" instead of "VO".

**Comment by tswinb** [comment]
Should we change the filter/variable label from "VO" to "Activity" as well as the graph titles?

And should we standardise on "Provider" instead of "Site"? (Or even standardise back to "Site"?)
