### ISSUE TITLE
Remove unnecessary time range options

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#39]
Any time option less than 30 days doesn't make a lot of sense, so the list could be tidied up. Looks like the options are in the JSON.

**Comment by tswinb** [comment]
This issue was raised previously [here](https://github.com/grafana/grafana/issues/14915)

"Sorry to tell you that at the moment you can't change the Quick ranges. Time options in json is a relic from older Grafana versions."

**Comment by tofu-rocketry** [comment]
Thanks for checking. We might have to think about a feature request then.

Can we remove the deprecated options at least?
