### ISSUE TITLE
Add more detail to resource centre (+ activity?) view

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#42]
Difficulty of validating data was raised at F2F meeting so if we can show the source of the data (SubmitHost?) then that would help.

(New monitoring system can also be extended to IRIS to help https://github.com/apel/monitoring)

**Comment by tswinb** [comment]
#52 adds panels to show SubmitHost

**Comment by tofu-rocketry** [comment]
We'll close this with #52. We can open a new issue if people raise other things they'd like.
