### ISSUE TITLE
Double counting in Resource Manager chart?

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#45]
Adding up both columns seems to suggest that some sites/VOs might be being included in both columns. This behaviour _might_ be ok, but we should see if it's acceptable and if it is, then clarify it on the chart. Otherwise, we'll have to fix it.

**Comment by tswinb** [comment]
I have been through and added up the projected values from the table by hand (making sure to separate out grid and cloud when a VO has both), and my figures match the totals in the graph/chart - so I think it's correctly splitting into the two bars without double counting.

**Comment by tofu-rocketry** [comment]
OK, sounds good. Thanks for checking.
