### ISSUE TITLE
Duplicated sites & VOs where both grid and cloud used

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#46]
We need to figure out a more elegant way of handling these cases as it is confusing to users.

Also covers situations of different capitalisation for different types of resource.

**Comment by tswinb** [comment]
One solution would be to rename them as they come in to Grafana to show whether they are grid or cloud. e.g. lsst_grid, lsst_cloud.

**Comment by tofu-rocketry** [comment]
This is now sorted with the new views in the IRIS schema.
