### ISSUE TITLE
Add links back to IRIS website, STFC, other?

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#5]

**Comment by tswinb** [comment]
Probably best placed on a welcome page/overview dashboard if multiple dashboards are needed.
Can use [Grafana stylesheet ](https://github.com/grafana/grafana/tree/master/public/sass)to style buttons: e.g.
![image](https://user-images.githubusercontent.com/18294786/65047703-cceed900-d95a-11e9-9eeb-b6880b8fa714.png)

**Comment by tswinb** [comment]
Grafana also natively supports links that sit inline with the variable selection but on the right hand side of the screen: 
![image](https://user-images.githubusercontent.com/18294786/66133816-37587800-e5ef-11e9-8a2e-8eb16811eaea.png)
This would be a fairly discreet way of having the links on any page.

**Comment by tofu-rocketry** [comment]
> Grafana also natively supports links that sit inline with the variable selection but on the right hand side of the screen:

Yeah, I think that looks better.

**Comment by tofu-rocketry** [comment]
We'll stick to just a link to the IRIS page for now.
