### ISSUE TITLE
Possibly map virgo to LIGO

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#7]
LIGO are apparently doing their work under the virgo VO.

Mapping it would be _a_ solution, but not the best, in case they do correct how they submit work and virgo start doing their own work.

**Comment by tswinb** [comment]
Can simply do 
`CASE` 
      `WHEN VO = 'virgo' THEN 'LIGO'`
      `ELSE VO`
`END 
AS VO`
in select statements.

**Comment by tofu-rocketry** [comment]
We could escalate this question as a fudge we use only for IRIS, but I'm not keen on changing this at the display end.

If they want the data to display under the right VO, LIGO should submit work with the right credentials and then request us to update the existing data in the database so long as they can distinguish between their usage and anything which should still be under 'virgo'.
