### ISSUE TITLE
Some email domains not able to log in with IAM

### ISSUE THREAD

**Issue by tofu-rocketry** [apel/grafana-dashboards#71]
Someone with a `ukaea.uk` email address couldn't log in using IAM, being given the "Login Failed Required email domain not fulfilled" error.

This shouldn't be a problem as that domain is listed in `allowed_domains`. Does Grafana have a limit on the number of domains it checks from that setting, or does it require domains with a certain number of elements?

**Comment by tofu-rocketry** [comment]
Changing the domain for `stfc.ac.uk` to something else and restarting the server works to stop me logging in using IAM and putting it back lets me in again, so the whitelisting works in general.

Does it not recognise `.uk` as a valid top level domain?

**Comment by tofu-rocketry** [comment]
Putting `stfc.ac.uk` at the end of the list still works, so it's not complaining about the length of the list.

**Comment by tofu-rocketry** [comment]
`ukaea.uk` is now fine, but cardiff and ligo don't seem to work.

**Comment by tofu-rocketry** [comment]
Everyone seems to have been able to log in somehow now.

**Comment by saerdnaer** [comment]
For future reference:

https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/google/#enable-google-oauth-in-grafana
